#!/bin/bash
set -euo pipefail

if [ -n "${1+x}" ]; then
	COUNT="$1"
else
	COUNT="1"
fi
# We actually want word splitting on the $(...) bit
# shellcheck disable=SC2046
WAYLAND_DISPLAY=wayland-0 ydotool search --onlyvisible --class Chromium key $(for ((i=0; i<$COUNT;++i)); do echo -n "ctrl+F4 "; done)
