#!/bin/bash
# TV Volume Up (raises media box volume through CEC)

deltapercent="$1"

[[ -z $deltapercent ]] && deltapercent=5

#NOW=$((0x$( (echo "tx 05:71" && sleep 5.0 && echo "q") | cec-client -d 8 | grep ">> 50:7a" | sed -u -E "s/.*50:7a://g" )))
#echo $NOW
#NOW=$( pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )

#if (( NOW+deltapercent > 100 )); then
#    echo "Please increase the volume on the amplifier";
#    pactl set-sink-mute "$sinkname" 0
#    pactl set-sink-volume "$sinkname" 100%
#else
#    pactl set-sink-mute "$sinkname" 0
#    pactl set-sink-volume "$sinkname" +$deltapercent%
#fi

#NOW=$( pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )

#echo "Volume: $NOW%"

if (( $deltapercent > 0 )); then
    (for ((i=0; i<$deltapercent; i++)); do echo "tx 05:44:41" && sleep 0.05 ; done; echo "q") | stdbuf -oL cec-client -d 8 | stdbuf -oL grep ">> 50:7a" | stdbuf -oL sed -E "s/.*50:7a:/0x/g" | stdbuf -oL xargs -n 1 printf "%d\x25\n"
else
    tvd "-$deltapercent"
fi

#(echo "tx 05:44:41" && sleep 0.05 && echo "tx 05:45" && sleep 1.0 && echo "q") | cec-client -d 8 | grep ">> 50:7a" | sed -u -E "s/.*50:7a:/0x/g" | xargs stdbuf -oL printf "Final volume: %d\x25\n"

#echo "done"

#echo "hi" && echo $FINAL_VOLUME_HEX
