#!/bin/bash

if (( $1 > 0 )); then
    for i in $(seq $1); do
        k VolumeUp
    done
else
    for i in $(seq $(($1*-1))); do
        k VolumeDown
    done
fi

exit


SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPT_DIR/scripts.sh

deltapercent="$1"

[[ -z $deltapercent ]] && deltapercent=15

sinkname=$(getsinkname)

NOW=$( pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )

if (( NOW+deltapercent > 100 )); then
    echo "Please increase the volume on the amplifier";
    pactl set-sink-mute "$sinkname" 0
    pactl set-sink-volume "$sinkname" 100%
else
    pactl set-sink-mute "$sinkname" 0
    pactl set-sink-volume "$sinkname" +$deltapercent%
fi

NOW=$( pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )

echo "Volume: $NOW%"
