#!/bin/bash

link="$*"

# if firefox is already open it takes 
# less time to open a new tab
sleeptime=10
if pgrep chrome; then
  sleeptime=6
fi

( browser "$link"
sleep "$sleeptime"
k f ) &

sleep 2
k 0
