#!/bin/bash

source /home/east/bin/scripts.sh

deltapercent="$1"

[[ -z $deltapercent ]] && deltapercent=15

sinkname=$(getsinkname)

pactl set-sink-volume "$sinkname" -$deltapercent%

NOW=$( pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )
echo "Volume: $NOW%"
if (( NOW < 60 )); then
    echo "Please decrease the volume on the amplifier to reduce the volume further";
fi
